name: sky_ways
description: "The skytrade features app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  hydrated_bloc: ^9.1.5
  dartz: ^0.10.1
  get_it: ^7.7.0
  path_provider: ^2.1.3
  json_annotation: ^4.9.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  web3auth_flutter: ^5.0.2
  mapbox_maps_flutter: ^2.0.0
  freezed_annotation: ^2.4.1
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.1
  dio: ^5.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  very_good_analysis: ^6.0.0
  mockito: ^5.4.4
  json_serializable: ^6.8.0
  package_rename_plus: ^1.0.1
  freezed: ^2.5.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - .env.dev
    - .env.stage
    - .env.live

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin-100.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-Thin-100-Italic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight-200.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLight-200-Italic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light-300.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Light-300-Italic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular-400.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Regular-400-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium-500.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Medium-500-Italic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold-600.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBold-600-Italic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold-700.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Bold-700-Italic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold-800.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBold-800-Italic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black-900.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-Black-900-Italic.ttf
          style: italic
          weight: 900
