name: sky_trade
description: "The SkyTrade Air Management app"

publish_to: 'none'

version: 0.0.5+5

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  app_links: ^6.3.3
  app_tracking_transparency: ^2.0.6+1
  auth0_flutter: ^1.8.0
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  cupertino_icons: ^1.0.6
  dart_geohash: ^2.1.0
  dartz: ^0.10.1
  dio: ^5.5.0+1
  equatable: ^2.0.7
  firebase_analytics: ^10.8.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_blue_plus: ^1.32.12
  flutter_clarity:
    git:
      url: https://github.com/microsoft/clarity-flutter-preview
      ref: main
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_opendroneid: ^0.19.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  geodart: ^0.3.6
  geolocator: ^13.0.1
  get_it: ^7.7.0
  hydrated_bloc: ^10.0.0
  internet_connection_checker_plus: ^2.5.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  mapbox_maps_flutter: ^2.6.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  rxdart: ^0.28.0
  sentry_dart_plugin: ^2.4.1
  sentry_flutter: ^8.14.0
  shared_preferences: ^2.3.3
  single_factor_auth_flutter: ^6.0.1
  socket_io_client: ^3.0.0-beta.2
  solana: ^0.31.0
  syncfusion_flutter_charts: ^27.1.52
  url_launcher: ^6.3.0
  uuid_v4: ^1.0.2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.7.0
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  package_rename_plus: ^1.0.1
  test: ^1.25.2
  very_good_analysis: ^6.0.0

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true

flutter_gen:
  output: lib/core/assets/generated
  line_length: 80

  integrations:
    flutter_svg: true

  assets:
    exclude:
      - .env.*

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/pngs/
    - .env.dev
    - .env.stage
    - .env.live

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin-100.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-Thin-100-Italic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight-200.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLight-200-Italic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light-300.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Light-300-Italic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular-400.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Regular-400-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium-500.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Medium-500-Italic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold-600.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBold-600-Italic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold-700.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Bold-700-Italic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold-800.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBold-800-Italic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black-900.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-Black-900-Italic.ttf
          style: italic
          weight: 900

    - family: Arial
      fonts:
        - asset: assets/fonts/arial/Arial-Regular-400.ttf
          weight: 400
        - asset: assets/fonts/arial/Arial-Bold-700.ttf
          weight: 700
