name: sky_ways
description: "The skytrade features app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  dart_geohash: ^2.1.0
  dartz: ^0.10.1
  dio: ^5.5.0+1
  equatable: ^2.0.5
  firebase_analytics: ^10.8.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  geodart: ^0.3.6
  geolocator: ^13.0.1
  get_it: ^7.7.0
  hydrated_bloc: ^9.1.5
  internet_connection_checker_plus: ^2.5.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  mapbox_maps_flutter: ^2.1.0
  path_provider: ^2.1.3
  rxdart: ^0.28.0
  sentry_dart_plugin: ^2.1.0
  sentry_flutter: ^8.8.0
  socket_io_client: ^3.0.0-beta.2
  url_launcher: ^6.3.0
  web3auth_flutter: ^5.0.2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  package_rename_plus: ^1.0.1
  very_good_analysis: ^6.0.0

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - .env.dev
    - .env.stage
    - .env.live

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin-100.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-Thin-100-Italic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight-200.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLight-200-Italic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light-300.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Light-300-Italic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular-400.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Regular-400-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium-500.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Medium-500-Italic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold-600.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBold-600-Italic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold-700.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Bold-700-Italic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold-800.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBold-800-Italic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black-900.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-Black-900-Italic.ttf
          style: italic
          weight: 900
