name: sky_trade
description: "The SkyTrade Air Management app"

publish_to: 'none'

version: 0.1.0+10

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  app_links: ^6.4.0
  app_tracking_transparency: ^2.0.6+1
  auth0_flutter: ^1.10.0
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dart_geohash: ^2.1.0
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_analytics: ^11.4.6
  firebase_core: ^3.13.1
  firebase_crashlytics: ^4.3.6
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_blue_plus: ^1.35.5
  flutter_clarity:
    git:
      url: https://github.com/microsoft/clarity-flutter-preview
      ref: main
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.5
  flutter_opendroneid: ^0.22.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  freezed_annotation: ^2.4.4
  geodart: ^0.3.7
  geolocator: ^14.0.0
  get_it: ^8.0.3
  hive_ce: ^2.11.2
  hive_ce_flutter: ^2.3.1
  hydrated_bloc: ^10.0.0
  internet_connection_checker_plus: ^2.7.2
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  mapbox_maps_flutter: ^2.8.0
  package_info_plus: ^8.1.3
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  qr_flutter: ^4.1.0
  rxdart: ^0.28.0
  sentry_dart_plugin: ^2.4.1
  sentry_flutter: ^8.14.2
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  single_factor_auth_flutter: ^7.0.0
  skeletonizer: ^2.0.1
  socket_io_client: ^3.1.2
  solana: ^0.31.0
  syncfusion_flutter_charts: ^29.2.5
  url_launcher: ^6.3.1
  uuid_v4: ^1.0.2
  webview_flutter: ^4.11.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  hive_ce_generator: ^1.9.1
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  package_rename_plus: ^1.0.2
  test: ^1.25.15
  very_good_analysis: ^7.0.0

flutter_gen:
  output: lib/core/assets/generated
  line_length: 80

  integrations:
    flutter_svg: true

  assets:
    exclude:
      - .env.*

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/pngs/
    - .env.dev
    - .env.stage
    - .env.live

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin-100.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-Thin-100-Italic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight-200.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLight-200-Italic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light-300.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Light-300-Italic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular-400.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Regular-400-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium-500.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Medium-500-Italic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold-600.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBold-600-Italic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold-700.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Bold-700-Italic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold-800.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBold-800-Italic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black-900.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-Black-900-Italic.ttf
          style: italic
          weight: 900

    - family: Arial
      fonts:
        - asset: assets/fonts/arial/Arial-Regular-400.ttf
          weight: 400
        - asset: assets/fonts/arial/Arial-Bold-700.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-SemiBold-600.otf
          weight: 600

    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Bold-700.ttf

    - family: ChakraPetch
      fonts:
        - asset: assets/fonts/chakra_petch/ChakraPetch-SemiBold-600.ttf
          weight: 600

    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400