name: sky_ways
description: "The skytrade features app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  hydrated_bloc: ^9.1.5
  dartz: ^0.10.1
  get_it: ^7.7.0
  path_provider: ^2.1.3
  json_annotation: ^4.9.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0
  web3auth_flutter: ^3.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  very_good_analysis: ^5.1.0
  mockito: ^5.4.4
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
